# Generated by Django 5.0.14 on 2025-07-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('swapi_id', models.IntegerField(default=0, help_text='0 for custom/unofficial records')),
                ('episode_id', models.IntegerField(blank=True, null=True)),
                ('opening_crawl', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('producer', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('swapi_id', models.IntegerField(default=0, help_text='0 for custom/unofficial records')),
                ('birth_year', models.CharField(blank=True, max_length=20, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mass', models.CharField(blank=True, max_length=50, null=True)),
                ('skin_color', models.CharField(blank=True, max_length=50, null=True)),
                ('homeworld', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('films', models.ManyToManyField(blank=True, related_name='characters', to='starwarsrest.film')),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('swapi_id', models.IntegerField(default=0, help_text='0 for custom/unofficial records')),
                ('starship_class', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('cost_in_credits', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('crew', models.CharField(blank=True, max_length=50, null=True)),
                ('passengers', models.CharField(blank=True, max_length=50, null=True)),
                ('max_atmosphering_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('hyperdrive_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('mglt', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('consumables', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('films', models.ManyToManyField(blank=True, related_name='starships', to='starwarsrest.film')),
                ('pilots', models.ManyToManyField(blank=True, related_name='starships', to='starwarsrest.character')),
            ],
            options={
                'unique_together': {('name', 'model')},
            },
        ),
    ]
