# Generated by Django 5.0.14 on 2025-07-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsrest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='starship',
            options={'ordering': ['name', 'model']},
        ),
    ]
